package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

filegroup(
    name = "all",
    srcs = glob(["**"]),
)

filegroup(
    name = "aes_gcm_siv",
    srcs = ["aes_gcm_siv_test.json"],
)

filegroup(
    name = "aes_gcm",
    srcs = ["aes_gcm_test.json"],
)

filegroup(
    name = "dsa",
    srcs = ["dsa_test.json"],
)

filegroup(
    name = "ecdsa",
    srcs = ["ecdsa_test.json"],
)

filegroup(
    name = "rsa_signature",
    srcs = ["rsa_signature_test.json"],
)

filegroup(
    name = "ecdsa_webcrypto",
    srcs = ["ecdsa_webcrypto_test.json"],
)

filegroup(
    name = "ecdh_webcrypto",
    srcs = ["ecdh_webcrypto_test.json"],
)
